// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ThemeSwitcher
{
    internal sealed partial class Vsix
    {
        public const string Id = "ThemeSwitcher.26e69bc4-ab86-469a-ac8e-f9f16e77ff7e";
        public const string Name = "Theme Switcher";
        public const string Description = @"Makes it easy to switch between any installed theme by exposing them in a dynamic menu";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
