// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ThemeSwitcher
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ThemeSwitcherString = "3ae3415b-d5b6-4f59-857a-ea156e70ac71";
        public static Guid ThemeSwitcher = new Guid(ThemeSwitcherString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ThemeMenu = 0x0001;
        public const int ThemeListGroup = 0x0002;
        public const int ThemeSettings = 0x0003;
        public const int GetMoreThemes = 0x0100;
        public const int FirstTheme = 0x0101;
    }
}